[release]
address = "0.0.0.0"
port = 9999
secret_key = "ySYyxmd8dbXr2quW4NdMm3CgPpA2lV7bxHpsjoElxjQuWDZQH2NMo7txXsHfJtwKNi22Ir4FSKATkHExxtIWP9lH"

[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"